### ISSUE TITLE
Database update logs are logged to stderr

### ISSUE THREAD

**Issue by bfil** [kubernetes-sigs/dashboard-metrics-scraper#31]
The dashboard-metrics-scraper pod writes the following logs to stderr every minute:

```
{ "level": "info", "msg": "Database updated: 1 nodes, 20 pods" }
```

It would be better to log these to stdout since they are info level logs.

I've also noticed a red herring in the server code when setting up the logger, where the comment says "Output to stdout instead of the default stderr", but [the code does the opposite](https://github.com/kubernetes-sigs/dashboard-metrics-scraper/blob/1e80bc3a67f75b3170cb715218ec38c10f9a8f12/server.go#L34-L36): 

```
log.SetOutput(os.Stderr)
```

**Comment by AndrewDryga** [comment]
There are people that believe that progress logs should be also written to stderr and if that's how maintainers decide to keep it - we need a way to filter out INFO level logs entirely, otherwise, our stackdriver logs are filled with errors. For Stackdriver everything in stderr is an error unless your JSON has `severity` property set to `info` and there is no way to change that.

Maybe we can add a JSON log format option which would use `severity` field instead of `level`?

**Comment by AndrewDryga** [comment]
A similar issue exists in external-dns: https://github.com/kubernetes-sigs/external-dns/issues/1616

**Comment by pierluigilenoci** [comment]
@bfil I did this https://github.com/kubernetes-sigs/dashboard-metrics-scraper/pull/45
Somehow it solves the question.

For the log level you can just use the `--log-level=warn` option.
